In [12]:
# Numpy: É utilizado para trabalhar com (Arrays) 

import numpy as np
import sys 

In [13]:
a = [1, 2, 3, 4, 5]
b = np.array([1, 2, 3, 4, 5])

In [14]:

print(a) # UMA LISTA
print(b) # UM ARRAY

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [17]:
# O TAMANHO DA MINHA LISTA

sys.getsizeof(a)

104

In [20]:
# O TAMANHO DO MEU ARRAY

b.nbytes

40

In [23]:
# ARRAY 1D

d1 = np.array([1, 2, 3])
print(d1)

[1 2 3]


In [24]:
# .shape É USADO PARA SABER O FORMATO 

d1.shape

(3,)

In [25]:
# .ndim É USADO PARA SABER A DIMENSÃO 

d1.ndim

1

In [26]:
# .dtype É USADO PARA SABER O TIPO 

d1.dtype

dtype('int64')

In [27]:
# ARRAY 2D

d2 = np.array([[1, 2, 3], [4, 5, 6]])
print(d2)

[[1 2 3]
 [4 5 6]]


In [28]:
# .shape É USADO PARA SABER O FORMATO 

d2.shape

(2, 3)

In [29]:
# .ndim É USADO PARA SABER A DIMENSÃO 

d2.ndim

2

In [30]:
# .dtype É USADO PARA SABER O TIPO 

d2.dtype

dtype('int64')

In [31]:
# ARRAY 3D

d3 = np.array([[[1, 2], [3,4]], [[5, 6], [7, 8]]])
print(d3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [32]:
# .shape É USADO PARA SABER O FORMATO 

d3.shape

(2, 2, 2)

In [33]:
# .ndim É USADO PARA SABER A DIMENSÃO 

d3.ndim

3

In [34]:
# .dtype É USADO PARA SABER O TIPO 

d3.dtype

dtype('int64')

In [42]:
lista1 = np.array([2, 3, 4])
lista2 = np.array([2, 3, 4])

In [44]:
# SOMANDO DUAS ARRAYS USANDO np.add

result = np.add(lista1, lista2)
print(result)

[4 6 8]


In [45]:
lista01 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(lista01)

[[1 2 3 4]
 [5 6 7 8]]


In [69]:
# SELECIONANDO ITENS EM ARRAYS
# array[row, column]

lista01[1, 3]

np.int64(8)

In [70]:
# PUXANDO TODOS OS ITENS DE UM ARRAY

lista01[0,:]

array([1, 2, 3, 4])

In [72]:
# PUXANDO DOIS ITENS EM ARRAYS DA MESMA COLUNAS MAS EM ARRYS DIFERENTES

lista01[:, 1]

array([2, 6])